### ISSUE TITLE
Unsuccessful HTTP response

### ISSUE THREAD

**Issue by BradGamez** [IntriguingTiles/cleverbot-free#11]
`(node:7156) UnhandledPromiseRejectionWarning: Error: Not Found
    at Request.callback (C:\Users\bradp\OneDrive\Desktop\w\node_modules\superagent\lib\node\index.js:883:15)
    at IncomingMessage.<anonymous> (C:\Users\bradp\OneDrive\Desktop\w\node_modules\superagent\lib\node\index.js:1126:20)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:7156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag '--unhandled-rejections=strict' (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7156) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I'm getting this error. I assume it was due to a change by Cleverbot API so it broke the package.

**Comment by xErik444x** [comment]
make a npm update, it is already fixed.

**Comment by BradGamez** [comment]
Thank you.
