### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by ammaraslam10** [IntriguingTiles/cleverbot-free#40]
```
Error: Forbidden
    at Request.callback (F:\node_modules\cleverbot-free\node_modules\superagent\lib\node\index.js:921:17)
    at IncomingMessage.<anonymous> (F:\node_modules\cleverbot-free\node_modules\superagent\lib\node\index.js:1165:20)
    at IncomingMessage.emit (node:events:532:35)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  status: 403,

```
Cleverbot opens fine on browser

```
      _header: 'GET /extras/conversation-social-min.js?20220528 HTTP/1.1\r\n' +
        'Host: www.cleverbot.com\r\n' +
        'Accept-Encoding: gzip, deflate\r\n' +
        'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36\r\n' +
        'Connection: close\r\n' +
        '\r\n',
    ...
    text: '<html>\r\n' +
      '<head><title>403 Forbidden</title></head>\r\n' +
      '<body bgcolor="white">\r\n' +
      '<center><h1>403 Forbidden</h1></center>\r\n' +
      '<hr><center>nginx/1.14.0</center>\r\n' +
      '</body>\r\n' +
      '</html>\r\n' +
      '<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n' +
      '<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n' +
      '<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n' +
      '<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n' +
      '<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n' +
      '<!-- a padding to disable MSIE and Chrome friendly error page -->\r\n',
```

**Comment by IntriguingTiles** [comment]
You've been banned from Cleverbot. If you have an ipv6 address, add
```
2a02:2498:e006:b::4 cleverbot.com
2a02:2498:e006:b::4 www.cleverbot.com
```
to your `/etc/hosts` to force node to use ipv6 instead of ipv4.

**Comment by ammaraslam10** [comment]
Oh nice, it worked, any chance they'll ban me again?

**Comment by IntriguingTiles** [comment]
It's certainly possible, though I've been using this for a couple months and so far it's been fine. I wonder if they even have ipv6 banning implemented on their side.
